INSERT INTO `courses` 
            (`id`, 
             `course_name`, 
             `course_address`, 
             `course_phone_number`, 
             `course_postal_code`, 
             `course_website`, 
             `course_email`, 
             `course_price`, 
             `country_id`, 
             `state_id`, 
             `city_id`, 
             `course_holes`, 
             `gold_tee_length`, 
             `blue_tee_length`, 
             `white_tee_length`, 
             `red_tee_length`, 
             `gold_tee_slope_rating`, 
             `blue_tee_slope_rating`, 
             `white_tee_slope_rating`, 
             `red_tee_slope_rating`, 
             `driving_range`, 
             `chipping_green`, 
             `putting_green`, 
             `practice_bunker`, 
             `pull_carts`, 
             `motorized_carts`, 
             `pro_shop`, 
             `golf_lessons`, 
             `caddies`, 
             `lockers`, 
             `restaurant`, 
             `created_at`, 
             `updated_at`) 
VALUES      (1, 
             'Billy Caldwell', 
             '6150 N Caldwell Avenue', 
             '+1 (773) 792-1930', 
             '60646', 
             'https://billycaldwell.forestpreservegolf.com', 
             NULL, 
             '$', 
             231, 
             3934, 
             44173, 
             NULL, 
             NULL, 
             NULL, 
             NULL, 
             NULL, 
             NULL, 
             NULL, 
             NULL, 
             NULL, 
             NULL, 
             1, 
             1, 
             NULL, 
             1, 
             1, 
             1, 
             NULL, 
             NULL, 
             NULL, 
             NULL, 
             '2017-09-30 18:34:57', 
             '2017-09-30 18:34:57'), 
            (2, 
             'Chick Evans Golf Course', 
             '6145 Golf Rd.', 
             '+1 (847) 965-5353', 
             '60053', 
             'https://chickevans.forestpreservegolf.com', 
             NULL, 
             '$', 
             231, 
             3934, 
             44173, 
             NULL, 
             NULL, 
             NULL, 
             NULL, 
             NULL, 
             NULL, 
             NULL, 
             NULL, 
             NULL, 
             NULL, 
             1, 
             1, 
             NULL, 
             1, 
             1, 
             1, 
             NULL, 
             NULL, 
             NULL, 
             NULL, 
             '2017-09-30 18:38:02', 
             '2017-09-30 18:38:02'), 
            (3, 
             'Highland Woods Golf Course', 
             '2775 Ela Road', 
             '+1 (847) 359-5850', 
             '60192', 
             'https://highlandwoods.forestpreservegolf.com', 
             NULL, 
             '$', 
             231, 
             3934, 
             44239, 
             NULL, 
             NULL, 
             NULL, 
             NULL, 
             NULL, 
             NULL, 
             NULL, 
             NULL, 
             NULL, 
             1, 
             1, 
             1, 
             NULL, 
             1, 
             1, 
             1, 
             1, 
             NULL, 
             NULL, 
             1, 
             '2017-09-30 18:40:40', 
             '2017-09-30 18:40:40'); 